<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
	<LangVersion>8.0</LangVersion>
    <Version>1.0</Version>
    <Title>ParkingDemo</Title>
    <Description>Description of ParkingDemo</Description>
    <TargetExt>.gha</TargetExt>
  </PropertyGroup>
	
  <ItemGroup>
    <Compile Remove="Component\Analyze\GetPathLength.cs" />
    <Compile Remove="Component\Analyze\SetOptimizationWeights.cs" />
    <Compile Remove="Component\Generation\ColumnGenerator.cs" />
    <Compile Remove="Component\Generation\ParkingPathConnection.cs" />
    <Compile Remove="Component\Generation\ParkingPathsTest.cs" />
    <Compile Remove="Component\Generation\PathConnection.cs" />
    <Compile Remove="Component\Preview\BakeParkingPreview.cs" />
    <Compile Remove="Component\Preview\PreviewParking.cs" />
    <Compile Remove="Component\Start\StartGeneration.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="7.13.21348.13001" IncludeAssets="compile;build" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="Copy &quot;$(TargetPath)&quot; &quot;C:\Users\fateme\AppData\Roaming\Grasshopper\Libraries\ParkingDemo.gha&quot;&#xD;&#xA;Erase &quot;$(TargetPath)&quot;" />
  </Target>

</Project>